# Generated by Django 5.0.1 on 2024-01-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0002_certification_email_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='Institution',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
