# Generated by Django 5.0.1 on 2024-01-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0003_certification_institution_certification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
