# Generated by Django 5.0.1 on 2024-01-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0004_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
