# Generated by Django 5.0.1 on 2024-01-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0005_alter_certification_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
